CREATE TABLE memorial_letters (
    id UUID PRIMARY KEY,
    memorial_id UUID NOT NULL UNIQUE REFERENCES memorials(id) ON DELETE CASCADE,
    subject VARCHAR(80),
    body VARCHAR(3000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
