import { expect, test } from '@playwright/test'

test('habitat preserves customization and offers accessible low-pressure interactions', async ({ page }) => {
  await page.goto('/habitat/play')
  await page.getByRole('button', { name: '兔子', exact: true }).click()
  await page.getByRole('button', { name: '起个名字' }).click()
  await page.getByLabel('小伙伴的名字').fill('团团')
  await page.getByRole('button', { name: '保存名字' }).click()
  await page.getByRole('button', { name: '摸摸它' }).click()
  await expect(page.getByRole('status')).toContainText('团团安静地靠在你身边')
  await page.getByRole('button', { name: '溪石浅滩', exact: true }).click()
  await page.getByRole('button', { name: '添一株水草' }).click()
  await page.reload()
  await expect(page.getByRole('heading', { name: '团团', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '溪石浅滩', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByText('水草 6 株 · 小鱼 5 尾')).toBeVisible()
  await page.getByRole('button', { name: '投喂小鱼', exact: true }).click()
  await expect(page.getByRole('button', { name: '小鱼正在吃饭' })).toBeDisabled()
  await page.getByRole('button', { name: '暂停动态' }).click()
  await expect(page.locator('.habitat')).toHaveClass(/is-paused/)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.habitat')).toHaveClass(/is-paused/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/habitat-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: 'test-results/habitat-desktop.png', fullPage: true })
})
