import { expect, test } from '@playwright/test'

test('pixel studio preserves a placed memory and exports a card', async ({ page }) => {
  await page.goto('/habitat')
  await page.getByRole('button', { name: /记忆灯 让一束光留下/ }).click()
  await page.locator('.artboard').press('Enter')
  await expect(page.getByRole('button', { name: '收回记忆灯', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '记忆', exact: true }).click()
  await page.getByLabel('这处风景，为谁而留').fill('小满')
  await page.getByLabel('记忆发生的日期').fill('2024-06-08')
  await page.getByLabel('想起的那个瞬间').fill('那天下午，你在窗边睡了很久。')
  await page.getByRole('button', { name: '收好这段记忆' }).click()
  await page.reload()
  await expect(page.getByText('那天下午，你在窗边睡了很久。', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '收回记忆灯', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '窗边旧时光', exact: true }).click()
  await page.getByRole('button', { name: '摸摸小猫', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('小猫')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出纪念卡 ↗', exact: true }).click()
  expect((await download).suggestedFilename()).toBe('光里的纪念卡.png')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: 'test-results/studio-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/studio-mobile.png', fullPage: true })
})
